"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.isRootNode = exports.isElementNode = exports.isTextNode = void 0;
const node_html_parser_1 = require("node-html-parser");
const isTextNode = (domNode) => domNode.nodeType === node_html_parser_1.NodeType.TEXT_NODE;
exports.isTextNode = isTextNode;
const isElementNode = (domNode) => domNode.nodeType === node_html_parser_1.NodeType.ELEMENT_NODE;
exports.isElementNode = isElementNode;
const isRootNode = (domNode) => (0, exports.isElementNode)(domNode) && domNode.parentNode == undefined;
exports.isRootNode = isRootNode;
